image: olamalu/node-rsync:16

pages:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - yarn
    - yarn build
    - mv dist public
    - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - master
