image: olamalu/node-rsync:16

pages:
  tags:
    - coryphe
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - yarn
    - yarn parcel build --target demo
    - mv dist/demo public
    - cp -R demo/public public
    - gzip -k -6 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - master

deploy_prod:
  tags:
    - coryphe
  stage: deploy
  script:
    - rsync -av public/ gitlab-runner@78.129.168.4:/var/www/gitlab-runner-static/miniatures.fitz.ms/
  environment:
    name: production
    url: https://minatures.fitzwilliam.ms
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
